### ISSUE TITLE
Having trouble resolving this error:  Uncaught TypeError: Cannot read property 'createBoard' of undefined

### ISSUE THREAD

**Issue by llevine** [llevine/chomper#1]
I am working on my game.js and trying to get the gameplay to work. I type game.start() into the debugger, and I get the following error: Uncaught TypeError: Cannot read property 'createBoard' of undefined. It does not like game.js line 10. I think the issue is due to how I am gathering the information from my api. I made a model for my api called trivia wrapper, and then I called it in a view on the game/index page. I am not sure if this was the correct way to populate the board, but it was the only way I could get the api's trivia to be accessible by my javascript. Not sure how to resolve the above issue. Help is greatly appreciated. @harimohanraj89 @DrRobotmck @htella

**Comment by DrRobotmck** [comment]
At first glance it doesn't look like your `game` object has a property `.board` which would explain the cannot read property of undefined error that you are getting.

I would suggest that you think about reorganizing the way that you are creating the game and accessing trivia information. I would suggest defining an onload function that would make an AJAX request to your server for the API information from the _GamesControllers_#**index**. Then, once that response is received attempt to create the new game board. It isn't the best practice to pass a variable into the view in a script tag since the views purpose is only to render data, not provide data for access in JS land (that's what AJAX is for). Look back at how we grabbed information from our server for the Hoot's app and HHMterest.

That should take care of the issues of not being able to create the game board in your game object, and also not being able to access the API information from your JavaScripts.

Hope that helps. Happy Holidays! And make sure to get some rest!

**Comment by htella** [comment]
Hey Lauren, was this resolved, or would you like some more help?
