### ISSUE TITLE
having some trouble with where I write my javascript

### ISSUE THREAD

**Issue by llevine** [llevine/chomper#3]
I am having a lot of trouble with my javascript. The javascript I currently have on my games/play.html.erb after line 3 used to be located in my application.js. The issue is when it was located in my application.js I kept getting an error that said triviaConnector is undefined. Therefor the first time I loaded the page playGame via the link on games/new the board would be blank, but if i refreshed the playGame page all of a sudden the information would be there. I am not sure how to get around this. Any javascript should only be used with the games/play.html.erb view. @harimohanraj89 @htella @DrRobotmck

**Comment by harimohanraj89** [comment]
Hey Lauren,

You should keep your javascript in your application.js file. The issue you are running into is a common problem with Rails applications because of sneaky stuff that Rails does in the background through a tool called "turbolinks". You can circumvent this problem by following the instructions in [this post](http://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links).

In essence, if your file looks like this right now:

``` js
$(function() {
  // do some stuff
});
```

then it needs to be modified to look like this:

``` js
var initialize = function() {
  // do some stuff
}

$(document).ready(initialize);
$(document).on('page:load', initialize);
```
